const createNewAttribute = {
  CREATE_NEW_ATTRIBUTE_FAILURE: 'CREATE_NEW_ATTRIBUTE_FAILURE',
  CREATE_NEW_ATTRIBUTE_SUCCESS: 'CREATE_NEW_ATTRIBUTE_SUCCESS',
  CREATE_NEW_ATTRIBUTE_REQUEST: 'CREATE_NEW_ATTRIBUTE_REQUEST',
}

const createNewChildrenAttribute = {
  CREATE_NEW_CHILDREN_ATTRIBUTE_FAILURE: 'CREATE_NEW_CHILDREN_ATTRIBUTE_FAILURE',
  CREATE_NEW_CHILDREN_ATTRIBUTE_SUCCESS: 'CREATE_NEW_ATTRIBUTE_SUCCESS',
  CREATE_NEW_CHILDREN_ATTRIBUTE_REQUEST: 'CREATE_NEW_CHILDREN_ATTRIBUTE_REQUEST',
}

const getAttributeList = {
  GET_ATTRIBUTE_LIST_REQUEST: 'GET_ATTRIBUTE_LIST_REQUEST',
  GET_ATTRIBUTE_LIST_FAILURE: 'GET_ATTRIBUTE_LIST_FAILURE',
  GET_ATTRIBUTE_LIST_SUCCESS: 'GET_ATTRIBUTE_LIST_SUCCESS',
}

const updateAttribute = {
  UPDATE_ATTRIBUTE_SUCCESS: 'UPDATE_ATTRIBUTE_SUCCESS',
  UPDATE_ATTRIBUTE_FAILURE: 'UPDATE_ATTRIBUTE_FAILURE',
  UPDATE_ATTRIBUTE_REQUEST: 'UPDATE_ATTRIBUTE_REQUEST',
}

const updateChilrenAttribute = {
  UPDATE_CHILDREN_ATTRIBUTE_SUCCESS: 'UPDATE_CHILDREN_ATTRIBUTE_SUCCESS',
  UPDATE_CHILDREN_ATTRIBUTE_FAILURE: 'UPDATE_CHILDREN_ATTRIBUTE_FAILURE',
  UPDATE_CHILDREN_ATTRIBUTE_REQUEST: 'UPDATE_CHILDREN_ATTRIBUTE_REQUEST',
}

const uiActions = {
  IS_UPDATE_FORM: 'IS_UPDATE_FORM'
}

const actionTypes = {
  ...createNewAttribute,
  ...createNewChildrenAttribute,
  ...getAttributeList,
  ...updateAttribute,
  ...updateChilrenAttribute,
  ...uiActions

}

export default actionTypes
