const createNewAttribute = {
  CREATE_NEW_ATTRIBUTE_FAILURE: 'CREATE_NEW_ATTRIBUTE_FAILURE',
  CREATE_NEW_ATTRIBUTE_SUCCESS: 'CREATE_NEW_ATTRIBUTE_SUCCESS',
  CREATE_NEW_ATTRIBUTE_REQUEST: 'CREATE_NEW_ATTRIBUTE_REQUEST',
}

const createNewChildrenAttribute = {
  CREATE_NEW_CHILDREN_ATTRIBUTE_FAILURE:
    'CREATE_NEW_CHILDREN_ATTRIBUTE_FAILURE',
  CREATE_NEW_CHILDREN_ATTRIBUTE_SUCCESS: 'CREATE_NEW_ATTRIBUTE_SUCCESS',
  CREATE_NEW_CHILDREN_ATTRIBUTE_REQUEST:
    'CREATE_NEW_CHILDREN_ATTRIBUTE_REQUEST',
}

const getAttributeList = {
  GET_ATTRIBUTE_LIST_REQUEST: 'GET_ATTRIBUTE_LIST_REQUEST',
  GET_ATTRIBUTE_LIST_FAILURE: 'GET_ATTRIBUTE_LIST_FAILURE',
  GET_ATTRIBUTE_LIST_SUCCESS: 'GET_ATTRIBUTE_LIST_SUCCESS',
}

const actionTypes = {
  ...createNewAttribute,
  ...createNewChildrenAttribute,
  ...getAttributeList,
}

export default actionTypes
