export const Data = [
    {
        id: Math.random(),
        month: 'Jan',
        benefit: 13000, 
        userLost: 200
    }, {
        id: Math.random(),
        month: 'Feb',
        benefit: 61000,
        userLost: 200
    }, {
        id: Math.random(),
        month: 'Mar',
        benefit: 22000,
        userLost: 200
    }, {
        id: Math.random(),
        month: 'Apr',
        benefit: 62000,
        userLost: 200
    }, {
        id: Math.random(),
        month: 'May',
        benefit: 33000,
        userLost: 200
    }, {
        id: Math.random(),
        month: 'Jun',
        benefit: 32000,
        userLost: 200
    }, {
        id: Math.random(),
        month: 'Jul',
        benefit: 77000,
        userLost: 200
    }, {
        id: Math.random(),
        month: 'Aug',
        benefit: 32000,
        userLost: 200
    }, {
        id: Math.random(),
        month: 'Sep',
        benefit: 122000,
        userLost: 200
    }, {
        id: Math.random(),
        month: 'Oct',
        benefit: 132000,
        userLost: 200
    }, {
        id: Math.random(),
        month: 'Nov',
        benefit: 162000,
        userLost: 200
    }, {
        id: Math.random(),
        month: 'Dec',
        benefit: 100000,
        userLost: 200
    },
]