const getUserProfile = {
    GET_USER_PROFILE_SUCCESS: 'GET_USER_PROFILE_SUCCESS',
    GET_USER_PROFILE_FAILURE: 'GET_USER_PROFILE_FAILURE',
    GET_USER_PROFILE_REQUEST: 'GET_USER_PROFILE_REQUEST'
}

export const actionTypes = { 
    ...getUserProfile
}